force_scale_x: 0.025 #0.07
force_scale_y: 0.025 #0.07
force_offset_x: 25.0 #100.0
force_offset_y: 0.0
speed_p_gain: 0.05
steering_p_gain: 0.7 # 1.0
steering_d_gain: 0.0
viz_forces_scale: 0.07
viz_net_force_scale: 0.014
